### ISSUE TITLE
Mark as watched not working

### ISSUE THREAD

**Issue by ms411** [CodeNinjaUK/youtube-subs-grid#80] opened 2016-03-31 00:57 UTC
I've tried loading chrome with just this one extension to ensure it wasn't a conflict with any other scripts or extensions, but I can't seem to get the [x] Mark as Watched to function since the latest update.

**Comment by DanSmith70** [comment] 2016-03-31 21:20
Hi, I think this might be related to #79 - Can you follow the same trouble shooting steps if possible? Thanks!

**Comment by ms411** [comment] 2016-03-31 23:30
Clicking the [x] does not cause anything to happen in the console. I get the same cast_sender.js net::ERR_FAILED as the other guy though if that matters.

Extensions set to sync

**Comment by chhe** [comment] 2016-04-08 16:40
I can confirm this behavior in Chrome 50.0.2661.66 beta-m. `[x] Mark as watched` seems to work though, you just have to reload the page manually and all marked items are hidden (depending on you setting whether you want to hide watched items of course). In the past this used to happen right after you clicked `[x] Mark as watched`. I can't see any error message in Chrome's Developer Console Log. Just the mentioned `net::ERR_FAILED`.

**Comment by Billy364** [comment] 2016-04-15 22:18
I started having this same issue 2-3 days ago. My Chrome is currently up to date on version 50.0.2661.75 m. I keep having to refresh the page whenever I want the "marked as watched" videos to be hidden, and it also keeps bringing up videos from years ago whenever I do so.

**Comment by DanSmith70** [comment] 2016-04-24 20:28
Sorry it took me a while to track this down - looks like Chrome did a stealth update or possibly fixed a bug that I was unwittingly relying on. Either way a fix should be rolling out shortly!

**Closed** 2016-04-24 20:29 UTC

**Comment by chhe** [comment] 2016-04-25 17:12
I can confirm "mark as watched" is working as usual again with version 1.18.2. Thanks!
